title_tag_text: Milinda Pathirage - Computer Science PhD Candidate
h1_tag_text: Milinda.

exclude: ["Procfile", "Gruntfile.js", "README.md", "package.json", "CNAME", "node_modules"]

highlighter: pygments
